title: Reference
description: This page serves as a reference work and contains topics that I have dealt with. 
theme: just-the-docs

url: https://mattk0stka.github.io

aux_links:
  Template Repository: https://mattk0stka.github.io/docs
